### ISSUE TITLE
c++20 coroutine based version is not as fast as the one using boost fiber?

### ISSUE THREAD

**Issue by npuichigo** [Tradias/asio-grpc#3]
Recently I ran the grpc_bench to compare the performance of different settings. I found the coroutine based one is slower than both the boost fiber version and the grpc multi-thread version. Do you have any insight about this?

**Comment by Tradias** [comment]
I have updated the benchmarks in the [README](https://github.com/Tradias/asio-grpc#performance). They actually show better performance with C++20 coroutines compared to Boost.Coroutine on my Linux machine.

Also note that if you are running benchmarks for 4 CPU servers then you really need to ensure that the server is fully exhausted. E.g. on my 12 core machine using 8 cores for the client and 4 for the server I am unable to do so:

| name                        |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
|-----------------------------|--------:|---------------:|---------------:|---------------:|---------------:|---------:|--------------:|
| go_grpc                     |   86840 |        8.74 ms |       16.41 ms |       19.92 ms |       28.71 ms |   247.3% |     28.08 MiB |
| cpp_grpc_callback           |   85723 |        9.97 ms |       15.16 ms |       17.95 ms |       24.42 ms |  215.32% |    158.87 MiB |
| cpp_asio_grpc_cpp20_coroutine |   84986 |        8.52 ms |       16.46 ms |       22.15 ms |       34.92 ms |  230.18% |     66.54 MiB |
| rust_tonic_mt               |   84591 |        9.04 ms |       17.39 ms |       22.55 ms |       34.38 ms |  281.41% |     18.87 MiB |
| cpp_grpc_mt                 |   83895 |        8.55 ms |       16.86 ms |       23.15 ms |       37.01 ms |  227.57% |     67.24 MiB |
| cpp_asio_grpc_boost_coroutine |   83631 |        8.66 ms |       16.96 ms |       22.62 ms |       36.11 ms |   231.3% |     66.75 MiB |
| rust_grpcio                 |   82151 |        9.31 ms |       17.01 ms |       22.90 ms |       36.57 ms |  274.72% |     34.45 MiB |
| rust_thruster_mt            |   79143 |        9.96 ms |       19.58 ms |       25.58 ms |       37.57 ms |  288.98% |     15.47 MiB |

Notice the `avg. cpu` column should be 400% for the server to be exhausted. Since it is not, these results are completely useless.

**Comment by Tradias** [comment]
For the upcoming version of asio-grpc I am planning to:

* Boost-less version that uses only standalone asio (already done on master)
* Initial support for unified executors with libunifex

**Comment by npuichigo** [comment]
Thanks for the info. I’d like to reproduce with my machine. By the way, will repeatedly_request improve the performance? What if there’s not enough request calls to match incoming requests?

**Comment by Tradias** [comment]
Yes good question. I couldn't find any information on "how many outstanding request calls" there should be at a time. Actually I just tested and it seems that if there are multiple outstanding calls to `RequestXXX` then all of them will handle the incoming RPC simultaneously. So I suppose that having exactly one is correct and that is what `repeatedly_request` is doing. E.g. the code in the benchmark could be rewritten to avoid coroutines entirely and only rely on callbacks which might yield better performance but I would say that such code is hardly scalable to real work applications:

```c++
struct ProcessRPC
{
    using executor_type = agrpc::GrpcContext::executor_type;

    agrpc::GrpcContext& grpc_context;

    auto get_executor() const noexcept { return grpc_context.get_executor(); }

    template <class RPCHandler>
    void operator()(RPCHandler&& rpc_handler, bool ok)
    {
        if (!ok)
        {
            return;
        }
        auto args = rpc_handler.args();
        auto response = std::allocate_shared<test::v1::Response>(grpc_context.get_allocator());
        response->set_integer(21);
        auto& response_ref = *response;
        agrpc::finish(std::get<2>(args), response_ref, grpc::Status::OK,
                      asio::bind_executor(this->get_executor(), [rpc_handler = std::move(rpc_handler),
                                                                 response = std::move(response)](bool) {}));
    }
};

agrpc::repeatedly_request(&test::v1::Test::AsyncService::RequestUnary, service, ProcessRPC{grpc_context});
```

**Comment by npuichigo** [comment]
Actually, I don't know whether it's necessary to align with theses lines to handle async requests.
```c++
} else if (status_ == PROCESS) {
      // Spawn a new CallData instance to serve new clients while we process
      // the one for this CallData. The instance will deallocate itself as
      // part of its FINISH state.
      new CallData(service_, cq_);

      // The actual processing.
      ...
```
That means, the coroutine version may be something like this:
```c++
awaitable<void> handle_rpc(UnaryRPCContext context) {
    helloworld::HelloReply response;
    response.set_message(context->request.name());
    auto &writer = context->writer;
    agrpc::finish(writer, response, grpc::Status::OK);
}

boost::asio::co_spawn(
      grpc_context,
      [&]() -> boost::asio::awaitable<void> {
        bool request_ok{true};
        auto executor = co_await this_coro::executor;
        while (request_ok) {
          auto context = std::allocate_shared<UnaryRPCContext>(
              grpc_context.get_allocator());
          request_ok = co_await agrpc::request(
              &helloworld::Greeter::AsyncService::RequestSayHello, service,
              context->server_context, context->request, context->writer);
          if (!request_ok) {
            guard.reset();
            co_return;
          }
          co_spawn(executor, handle_rpc(std::move(context)), detached);
        }
      },
      boost::asio::detached);
```
Even though the actuall processing time is long, there's still enough calls to `RequestXXX` with seperate coroutine to match the incoming requests.

**Comment by npuichigo** [comment]
I reruned the benchmark with my machine and the results are the consistent with yours.

However, it's strange that, after changing this [line](https://github.com/Tradias/grpc_bench/blob/master/cpp_asio_grpc_cpp20_coroutine_bench/main.cpp#L59) to `co_await agrpc::finish(writer, response, grpc::Status::OK);`, the performance is hurt significantly.

**Comment by npuichigo** [comment]
After switch to use co_spawn immediately after receiving the request, the `co_await agrpc::finish` version can get comparable benchmark results.

**Comment by Tradias** [comment]
Seems legitimate to me. I mean that is exactly what `repeatedly_request` helps with: To ensure that the next call to `Request` is being made immediately, even before handling the particular request. If you look at https://github.com/Tradias/asio-grpc#snippet-repeatedly-request-spawner you will see an example that does exactly what your change is doing, aka. spawn another coroutine to handle the `Finish` while already having made another call to `Request` in the background.

The performance with unifex might be slightly better since they can avoid the extra dynamic memory allocation for the `OperationState` and store it in the coroutine frame directly. Although if they do not have memory recycling for the `task` itself like Boost.Asio does for their `awaitable` it might even out.

**Comment by Tradias** [comment]
I am very glad for your input and your efforts on adapting asio-grpc to libunifex. I think we should combine our efforts. I am open to pull requests, issues and ideas in general. Currently thinking about how to design an API for the `Sender` concept that works with different "backend"s like Asio's `set_value` and libunifex's `set_value`.
There is a [CONTRIBUTING](https://github.com/Tradias/asio-grpc/blob/master/CONTRIBUTING.md) guideline that should get you started, as well as a `CMakePresets.json` that your IDE might find helpful.

**Comment by npuichigo** [comment]
Actually I have been following the recent proposals of how executor/network are landed in C++ standard. I did some efforts on adapting to libunifex for a more lightweight solution, since asio is not only related to executors. (maybe because I'm not so familiar with asio😀)

Now that you have already extended asio-grpc with libunifex support, maybe combine our efforts is a good way, and I am also willing to do some contribution for an easier-to-user async api. I will take a look up the recent updates and think about it.

For the rest, since uou mentioned before that we need some codegen to make things easier for users, my first though is to add some plugin like [this](https://github.com/Tencent/flare/blob/master/flare/rpc/protocol/protobuf/plugin/v2_plugin.cc) to provide some dummy codes. Then I'd like to refer to some C# grpc api for the designs.

**Comment by npuichigo** [comment]
Close as the issue is addressed now. Hope we can have further discussion in the futute.
