### ISSUE TITLE
assertion GRPC_CALL_ERROR_TOO_MANY_OPERATIONS in the example server code

### ISSUE THREAD

**Issue by khanhha** [Tradias/asio-grpc#7]
Hi, 
I am trying to run the example-server.cpp and example-client.cpp example from the version 1.1.2  [installed using vcpkg with boost container feature]. 

I got an assertion error GRPC_CALL_ERROR_TOO_MANY_OPERATIONS  at the following line in the server code
![image](https://user-images.githubusercontent.com/2276264/139867044-54e13c6d-149c-46d7-91c2-1f6fadabf029.png)

here is the stack trace when the assertion occurs.
![image](https://user-images.githubusercontent.com/2276264/139866704-ef3058ea-2ce9-422e-95e9-55558635e876.png)

here is the detail information about the assertion.
![image](https://user-images.githubusercontent.com/2276264/139866874-e4d3d2cd-184a-4208-8dd6-be1bf5e25b84.png)

do you have any idea why the bug happens?

**Comment by rbresalier** [comment]
I also observe this.

**Comment by khanhha** [comment]
@rbresalier  it is because of this line that causes the handler to be called twice. commenting it out will solve the problem.

![image](https://user-images.githubusercontent.com/2276264/139876975-ed189b58-2dff-4e24-b420-ec56fa26afba.png)

**Comment by rbresalier** [comment]
@khanhha : I still have same crash when I comment out that line :(

**Comment by rbresalier** [comment]
@khanhha: I'm still using October 26 version commit a17b559, don't know if going to latest version would solve this, I'll try that later.

**Comment by Tradias** [comment]
Hi guys, sorry for the confusion regarding these two examples. They are more meant as a mean to write documentation and show all possible options of the API. Does not mean that all options should be used at the same time or that the example itself even runs. I will move it out into the test/ section and provide some actually runnable examples for streaming RPCs. Again sorry for that.

To answer what is causing the error though:

1. gRPC allows only exactly one call to `finish`, `write_and_finish` or `finish_with_error` for a given RPC. Which means in the example one should either use `agrpc::finish` or `agrpc::finish_with_error` but not both.

2. Indeed in the `Spawner` for `repeatedly_request` only one of the two presented options should be used and the other removed: Either `std::apply(...)` or `std::invoke(...)`. Otherwise one RPC will be handled twice simultaneously.

**Comment by khanhha** [comment]
hi Tradias, thanks for your support and a wonderful library.
