### ISSUE TITLE
Question: Why is it recommended to create one agrpc::GrpcContext per thread?

### ISSUE THREAD

**Issue by eladm-ultrawis** [Tradias/asio-grpc#70]
Hi,

I read in the documentation that it is recommended to create a single thread per GrpcContext / completion queue.
When working with asio, I am used to create a **single** io_context and have multiple threads invoke io_context::run to handle completions.

So why is it recommended to create GrpcContext per thread? 
It might also be beneficial to create an example of using multiple threads per GrpcContext and also utilizing asio::strand to synchronize completion handlers.

Great library BTW.

**Comment by Tradias** [comment]
In the documentation I tried to emphasize that one GrpcContext should be created per thread as opposed to multiple contexts per thread. [Running one context on multiple threads is not supported](https://tradias.github.io/asio-grpc/classagrpc_1_1_grpc_context.html#acb1dae170b054aba4c83e266c456fee0). The documentation should probably make that more explicit in the `Detailed Description` section of the GrpcContext.

The idea of using one completion queue per thread comes from gRPC's [Performance Best Practices](https://grpc.io/docs/guides/performance/) which used to give that recommendation. Nowadays, it recommends one queue per two threads, but I don't want to have the additional synchronization overhead and complexity in my/user code.

To achieve multi-threading with this library you should create one thread per context as shown in this [client](https://github.com/Tradias/asio-grpc/blob/master/example/multi-threaded-client.cpp) and [server](https://github.com/Tradias/asio-grpc/blob/master/example/multi-threaded-server.cpp) example. You can then utilize one of the contexts for stranding activity.

**Comment by eladm-ultrawis** [comment]
@Tradias thanks. 

If possible, I think it might be beneficial make a version of GrpcContext that supports calling run from multiple threads. users may then choose to use asio::strand mechanism to synchronize completions.

I also think that this aspect needs better emphasis in the docs:
- it is redundant / impossible to use asio::strand
- it is prohibited to invoke run from multiple threads

**Comment by Tradias** [comment]
Thanks for the feedback, I am always eager to improve the documentation:

* I guess for this one I should refer to [Asio's documentation](https://www.boost.org/doc/libs/1_81_0/doc/html/boost_asio/overview/core/strands.html) which says that "Calling io_context::run() from only one thread means all event handlers execute in an implicit strand, due to the io_context's guarantee that handlers are only invoked from inside run()."
* I don't know how to make this [more clear](https://tradias.github.io/asio-grpc/classagrpc_1_1_grpc_context.html#acb1dae170b054aba4c83e266c456fee0) 😄
