### ISSUE TITLE
feature request: support cancel in agrpc::Alarm

### ISSUE THREAD

**Issue by eladm-ultrawis** [Tradias/asio-grpc#71]
As far as I can tell, there is no way to cancel the underlying alarm using agrpc::Alarm.

Is there a reason why this is not supported?

Thanks!

**Comment by Tradias** [comment]
You mean a member function like `agrpc::Alarm::cancel`? I didn't feel the need for it because cancellation can be done through asio/unifex's CancellationSlot/StopToken. But I guess, it should be easy to add.

**Comment by eladm-ultrawis** [comment]
Yes that's what I mean. In my case I implemented a wrapper around an alarm that has indefinite timeout, and I used the cancel method to wake-up the waiter. so it acts like some sort of async condition variable. 

Also, If we are talking about cancellation, I didn't quite get the cancellation mechanism in the library (CancelSafe?) 

Thanks!

**Comment by Tradias** [comment]
I see. If you just need an async condition variable you would be better of using a pure asio implementation (like [this](https://github.com/klemens-morgenstern/sam/blob/master/include/boost/sam/condition_variable.hpp)). Nonetheless, I will add the `cancel` member function as it makes sense.

CancelSafe is primarily meant to be used to write select-style code. Meaning, wait until one async operation out of a group of operations completes and cancel the wait on the other operations (without cancelling the operations themselves). I used to have an [example](https://github.com/Tradias/asio-grpc/blob/84c5a8e4730df93be04883e24c11a56605d44cc8/example/streaming-server.cpp#L191-L282) for it but it does not handle all edge cases. It was added because individual reads/writes from a gRPC stream cannot be cancelled but users wanted to perform them in asio's compound operations like [Co-ordinating Parallel Coroutines](https://www.boost.org/doc/libs/1_81_0/doc/html/boost_asio/overview/composition/cpp20_coroutines.html#boost_asio.overview.composition.cpp20_coroutines.co_ordinating_parallel_coroutines).

**Comment by Tradias** [comment]
Feature has been added with 2.6.0
