### ISSUE TITLE
Questions about CPU usage and event multiplexing

### ISSUE THREAD

**Issue by criatura2** [Tradias/asio-grpc#75]
Hi, we are considering using this library in a project and would like to clarify some things first

1. Our first choice would be to use a single thread as shown in [this example](https://github.com/Tradias/asio-grpc/blob/126eb3e6ca81921349f696a31669ac7842e3e280/example/share-io-context-client.cpp), but I have concers about the CPU usage: this strategy seems to be based on polling both the asio event loop ( `io_context` ) and the grpc completion queue with with a [zero timeout](https://github.com/Tradias/asio-grpc/blob/master/src/agrpc/detail/grpc_context.ipp#L111) to prevent the call to [AsyncNext](https://github.com/Tradias/asio-grpc/blob/126eb3e6ca81921349f696a31669ac7842e3e280/src/agrpc/detail/grpc_context_implementation.ipp#L165) from blocking. If that is the case, the loop is likely to consume 100% of one CPU core, which might be prohibitive to our customers. On the other hand if it uses a small timeout to avoid too high CPU usage, it might add latency since both event loops cannot run at the same time. Is this analysis correct?

2. Can I perform multiple concurrent calls to `RPC::request` (as shown [here](https://github.com/Tradias/asio-grpc/blob/126eb3e6ca81921349f696a31669ac7842e3e280/example/share-io-context-client.cpp#L59)) on the same context or should I wait the completion of last one to perform a new request?

Thanks.

**Comment by Tradias** [comment]
Hi, thanks for considering this library :).

1. Correct, without timeout this would consume 100% CPU. In `agrpc::run` I therefore use a backoff policy going from the default of [250ms](https://github.com/Tradias/asio-grpc/blob/126eb3e6ca81921349f696a31669ac7842e3e280/src/agrpc/run.hpp#L43) down to 0ms depending on most recent activity on either context. If a context has just processed them work in their poll call -> reduce timeout to 0ms, if not -> gradually increase back to 250ms. I am personally not a big fan of this API either, but users seem to like the convenience of running io_context and GrpcContext on the same thread (and thereby avoiding any need for synchronization). I feel that it needs more real-world testing though. I have some performance numbers for unary rpcs in the [README].(https://github.com/Tradias/asio-grpc#performance) (look for `cpp_asio_grpc_io_context_coro`).
2. Yes you can, otherwise it wouldn't be an asynchronous API, right? 😁

**Comment by criatura2** [comment]
Thanks

> Yes you can, otherwise it wouldn't be an asynchronous API, right?

In some low-level libraries like Boost.Beast the user is responsible for synchronizing reads and writes.

**Comment by Tradias** [comment]
> In some low-level libraries like Boost.Beast the user is responsible for synchronizing reads and writes.

For a single streaming RPC you can only have one outstanding read/write at a time. But of course, you can have multiple clients, each doing their RPC and won't need to sync reads/writes between all clients.
